add anime modal window
sparrrkling-vinegar/anirec pull request #12
Opened 2024-04-28 20:54 UTC by r-mol

- добавил modal window для описания аниме
- вернул строчку после разрешение конфликта

2024-04-29 04:51 UTC, y4cer commented on main.py
> +    user = get_current_user(token)
Разве раньше не было пользователя?

2024-04-29 04:51 UTC, y4cer commented on templates/internal/my_anime_list.html
> +                        <p style="cursor: pointer;" onclick="showAnimeDetails(${JSON.stringify(item).replace(/"/g, '&quot;')})">${item.title}</p>
Здесь возможно лучше использовать вот это https://stackoverflow.com/a/6234804. Вдруг что

2024-04-29 04:51 UTC, y4cer commented on templates/internal/recommendation.html
> +                    <p style="cursor: pointer;" onclick="showAnimeDetails(${JSON.stringify(item).replace(/"/g, '&quot;')})">${item.title}</p>
Ну и здесь соответственно тоже желательно заэскейпить https://stackoverflow.com/a/6234804

2024-04-29 11:51 UTC, NAD777 commented on main.py
> +    user = get_current_user(token)
Тут скорее надо отказаться от получения пользователя через user_service [ниже](https://github.com/sparrrkling-vinegar/anirec/blob/80b2e102b2261584671559ccd7f082905ab848f5/main.py#L195C9-L195C56). Потому и не надо хендлить exception, потому что если есть jwt мы в шоколаде

2024-04-29 11:51 UTC, NAD777 commented on main.py
> +    user = get_current_user(token)
Можно было бы поправить, будет более консистентно с другим ручками, это осталось с момента, когда у нас еще не было jwt, а была первая итерация интеграции

2024-04-29 18:48 UTC, vladdan16 requested changes

2024-04-29 18:48 UTC, vladdan16 commented on .github/workflows/main.yml
> -        run: poetry run bandit -r . -x ./test
верни exclude тестов

2024-04-29 19:06 UTC, vladdan16 submitted a review, later dismissed

2024-04-29 20:40 UTC, NAD777 submitted a review, later dismissed

2024-04-30 06:19 UTC, NAD777 approved these changes

2024-04-30 06:20 UTC, merged